
// This file contains all the UI text translations for the application.
// Separating this into its own file keeps the main service logic clean and concise.

export interface UIStrings {
    findTitle: string; findDesc: string; nearbyDoctors: string; nearbyHospitals: string; serialMonitor: string;
    cmdPlaceholder: string; send: string; viewHistory: string; autoTranslate: string; directions: string;
    whatsapp: string; phoneNotAvailable: string; language: string; bluetooth: string; usbSerial: string;
    disconnect: string; quickInfoTitle: string; quickInfoDesc: string;
    helplinesTitle: string; hospitalHelpline: string; police: string; ambulance: string; analyze: string;
    analyzing: string; aiAnalysis: string; aiAnalyzing: string; aiAnalysisFailed: string;
}

export const UI_STRINGS: Record<string, UIStrings> = {
  en: { findTitle:'Find Doctors', findDesc:'Search specialized doctors, view profile and get directions & contact.', nearbyDoctors:'Search nearby doctors', nearbyHospitals:'Search nearby hospitals', serialMonitor:'Serial Monitor', cmdPlaceholder:'Type a command or message to send', send:'Send', viewHistory:'View History:', autoTranslate: 'Auto-translate', directions: 'Directions', whatsapp: 'WhatsApp', phoneNotAvailable: 'Phone not available', language: 'Language', bluetooth: 'Bluetooth', usbSerial: 'USB Serial', disconnect: 'Disconnect', quickInfoTitle: 'Quick Info', quickInfoDesc: 'Use left panel to find doctors and helplines. Use center panel to connect to device and view logs.', helplinesTitle: 'Helplines', hospitalHelpline: 'Hospital helpline', police: 'Police', ambulance: 'Ambulance', analyze: 'Analyze', analyzing: 'Analyzing...', aiAnalysis: 'AI Analysis:', aiAnalyzing: 'Analyzing logs with AI...', aiAnalysisFailed: 'AI analysis failed:' },
  hi: { findTitle:'डॉक्टर खोजें', findDesc:'विशेषज्ञ डॉक्टर खोजें, प्रोफ़ाइल देखें तथा दिशानिर्देश व संपर्क प्राप्त करें।', nearbyDoctors:'निकट के डॉक्टर खोजें', nearbyHospitals:'निकट के अस्पताल खोजें', serialMonitor:'सीरियल मॉनिटर', cmdPlaceholder:'भेजने के लिए कमांड लिखें', send:'भेजें', viewHistory:'इतिहास देखें:', autoTranslate: 'स्वतः अनुवाद', directions: 'दिशा-निर्देश', whatsapp: 'व्हाट्सएप', phoneNotAvailable: 'फोन उपलब्ध नहीं', language: 'भाषा', bluetooth: 'ब्लूटूथ', usbSerial: 'यूएसबी सीरियल', disconnect: 'डिस्कनेक्ट', quickInfoTitle: 'त्वरित जानकारी', quickInfoDesc: 'डॉक्टरों और हेल्पलाइन को खोजने के लिए बाएं पैनल का उपयोग करें। डिवाइस से कनेक्ट करने और लॉग देखने के लिए केंद्र पैनल का उपयोग करें।', helplinesTitle: 'हेल्पलाइन', hospitalHelpline: 'अस्पताल हेल्पलाइन', police: 'पुलिस', ambulance: 'एम्बुलेंस', analyze: 'विश्लेषण', analyzing: 'विश्लेषण हो रहा है...', aiAnalysis: 'एआई विश्लेषण:', aiAnalyzing: 'एआई के साथ लॉग का विश्लेषण किया जा रहा है...', aiAnalysisFailed: 'एआई विश्लेषण विफल:' },
  bn: { findTitle: 'ডাক্তার খুঁজুন', findDesc: 'বিশেষজ্ঞ ডাক্তার খুঁজুন, প্রোফাইল দেখুন এবং দিকনির্দেশ ও যোগাযোগ পান।', nearbyDoctors: 'কাছাকাছি ডাক্তার খুঁজুন', nearbyHospitals: 'কাছাকাছি হাসপাতাল খুঁজুন', serialMonitor: 'সিরিয়াল মনিটর', cmdPlaceholder: 'পাঠানোর জন্য একটি কমান্ড বা বার্তা টাইপ করুন', send: 'পাঠান', viewHistory: 'ইতিহাস দেখুন:', autoTranslate: 'স্বয়ংক্রিয় অনুবাদ', directions: 'দিকনির্দেশ', whatsapp: 'হোয়াটসঅ্যাপ', phoneNotAvailable: 'ফোন উপলব্ধ নেই', language: 'ভাষা', bluetooth: 'ব্লুটুথ', usbSerial: 'ইউএসবি সিরিয়াল', disconnect: 'সংযোগ বিচ্ছিন্ন করুন', quickInfoTitle: 'দ্রুত তথ্য', quickInfoDesc: 'ডাক্তার এবং हेल्पलाइन খুঁজে পেতে বাম প্যানেল ব্যবহার করুন। ডিভাইসের সাথে সংযোগ করতে এবং লগ দেখতে কেন্দ্র প্যানেল ব্যবহার করুন।', helplinesTitle: 'হেল্পলাইন', hospitalHelpline: 'হাসপাতাল হেল্পলাইন', police: 'পুলিশ', ambulance: 'অ্যাম্বুলেন্স', analyze: 'বিশ্লেষণ করুন', analyzing: 'বিশ্লেষণ করা হচ্ছে...', aiAnalysis: 'এআই বিশ্লেষণ:', aiAnalyzing: 'এআই দিয়ে লগ বিশ্লেষণ করা হচ্ছে...', aiAnalysisFailed: 'এআই বিশ্লেষণ ব্যর্থ হয়েছে:' },
  ta: { findTitle: 'மருத்துவர்களைக் கண்டறியவும்', findDesc: 'சிறப்பு மருத்துவர்களைத் தேடுங்கள், சுயவிவரத்தைப் பார்க்கவும் மற்றும் திசைகள் மற்றும் தொடர்பைப் பெறவும்.', nearbyDoctors: 'அருகிலுள்ள மருத்துவர்களைத் தேடுங்கள்', nearbyHospitals: 'அருகிலுள்ள மருத்துவமனைகளைத் தேடுங்கள்', serialMonitor: 'தொடர் கண்காணிப்பு', cmdPlaceholder: 'அனுப்ப ஒரு கட்டளை அல்லது செய்தியைத் தட்டச்சு செய்யவும்', send: 'அனுப்பு', viewHistory: 'வரலாற்றைக் காண்க:', autoTranslate: 'தானாக மொழிபெயர்', directions: 'திசைகள்', whatsapp: 'வாட்ஸ்அப்', phoneNotAvailable: 'தொலைபேசி கிடைக்கவில்லை', language: 'மொழி', bluetooth: 'புளூடூத்', usbSerial: 'யூஎஸ்பி தொடர்', disconnect: 'துண்டிக்கவும்', quickInfoTitle: 'விரைவுத் தகவல்', quickInfoDesc: 'மருத்துவர்கள் மற்றும் உதவி எண்களைக் கண்டுபிடிக்க இடது பேனலைப் பயன்படுத்தவும். சாதனத்துடன் இணைவதற்கும் பதிவுகளைப் பார்ப்பதற்கும் மையப் பேனலைப் பயன்படுத்தவும்.', helplinesTitle: 'உதவி எண்கள்', hospitalHelpline: 'மருத்துவமனை உதவி எண்', police: 'காவல்துறை', ambulance: 'ஆம்புலன்ஸ்', analyze: 'பகுப்பாய்வு', analyzing: 'பகுப்பாய்வு செய்கிறது...', aiAnalysis: 'AI பகுப்பாய்வு:', aiAnalyzing: 'AI உடன் பதிவுகளை பகுப்பாய்வு செய்கிறது...', aiAnalysisFailed: 'AI பகுப்பாய்வு தோல்வியடைந்தது:' },
  te: { findTitle: 'డాక్టర్లను కనుగొనండి', findDesc: 'ప్రత్యేక వైద్యులను శోధించండి, ప్రొఫైల్ చూడండి మరియు దిశలు & పరిచయం పొందండి.', nearbyDoctors: 'సమీపంలోని డాక్టర్ల కోసం శోధించండి', nearbyHospitals: 'సమీపంలోని ఆసుపత్రుల కోసం శోధించండి', serialMonitor: 'సీరియల్ మానిటర్', cmdPlaceholder: 'పంపడానికి ఒక ఆదేశం లేదా సందేశం టైప్ చేయండి', send: 'పంపు', viewHistory: 'చరిత్రను వీక్షించండి:', autoTranslate: 'స్వయంచాలకంగా అనువదించు', directions: 'దిశలు', whatsapp: 'వాట్సాప్', phoneNotAvailable: 'ఫోన్ అందుబాటులో లేదు', language: 'భాష', bluetooth: 'బ్లూటూత్', usbSerial: 'USB సీరియల్', disconnect: 'డిస్‌కనెక్ట్ చేయండి', quickInfoTitle: 'త్వరిత సమాచారం', quickInfoDesc: 'డాక్టర్లు మరియు హెల్ప్‌లైన్‌లను కనుగొనడానికి ఎడమ ప్యానెల్‌ను ఉపయోగించండి. పరికరానికి కనెక్ట్ చేయడానికి మరియు లాగ్‌లను వీక్షించడానికి మధ్య ప్యానెల్‌ను ఉపయోగించండి.', helplinesTitle: 'హెల్ప్‌లైన్‌లు', hospitalHelpline: 'ఆసుపత్రి హెల్ప్‌లైన్', police: 'పోలీస్', ambulance: 'అంబులెన్స్', analyze: 'విశ్లేషించండి', analyzing: 'విశ్లేషిస్తోంది...', aiAnalysis: 'AI విశ్లేషణ:', aiAnalyzing: 'AIతో లాగ్‌లను విశ్లేషిస్తోంది...', aiAnalysisFailed: 'AI విశ్లేషణ విఫలమైంది:' },
  mr: { findTitle: 'डॉक्टर शोधा', findDesc: 'विशेषज्ञ डॉक्टर शोधा, प्रोफाइल पहा आणि दिशानिर्देश व संपर्क मिळवा.', nearbyDoctors: 'जवळपासचे डॉक्टर शोधा', nearbyHospitals: 'जवळपासची रुग्णालये शोधा', serialMonitor: 'सिरियल मॉनिटर', cmdPlaceholder: 'पाठवण्यासाठी कमांड किंवा संदेश टाइप करा', send: 'पाठवा', viewHistory: 'इतिहास पहा:', autoTranslate: 'स्वयं-अनुवाद', directions: 'दिशानिर्देश', whatsapp: 'व्हॉट्सॲप', phoneNotAvailable: 'फोन उपलब्ध नाही', language: 'भाषा', bluetooth: 'ब्लूटूथ', usbSerial: 'यूएसबी सिरियल', disconnect: 'डिस्कनेक्ट करा', quickInfoTitle: 'द्रुत माहिती', quickInfoDesc: 'डॉक्टर आणि हेल्पलाइन शोधण्यासाठी डाव्या पॅनेलचा वापर करा. डिव्हाइसशी कनेक्ट करण्यासाठी आणि लॉग पाहण्यासाठी मध्य पॅनेलचा वापर करा.', helplinesTitle: 'हेल्पलाइन', hospitalHelpline: 'रुग्णालय हेल्पलाइन', police: 'पोलीस', ambulance: 'रुग्णवाहिका', analyze: 'विश्लेषण करा', analyzing: 'विश्लेषण करत आहे...', aiAnalysis: 'एआय विश्लेषण:', aiAnalyzing: 'एआयसह लॉगचे विश्लेषण करत आहे...', aiAnalysisFailed: 'एआय विश्लेषण अयशस्वी झाले:' },
  gu: { findTitle: 'ડૉક્ટરો શોધો', findDesc: 'વિશિષ્ટ ડૉક્ટરો શોધો, પ્રોફાઇલ જુઓ અને દિશાઓ અને સંપર્ક મેળવો.', nearbyDoctors: 'નજીકના ડૉક્ટરો શોધો', nearbyHospitals: 'નજીકની હોસ્પિટલો શોધો', serialMonitor: 'સીરીયલ મોનિટર', cmdPlaceholder: 'મોકલવા માટે આદેશ અથવા સંદેશ લખો', send: 'મોકલો', viewHistory: 'ઇતિહાસ જુઓ:', autoTranslate: 'આપોઆપ અનુવાદ', directions: 'દિશાઓ', whatsapp: 'વોટ્સએપ', phoneNotAvailable: 'ફોન ઉપલબ્ધ નથી', language: 'ભાષા', bluetooth: 'બ્લૂટૂથ', usbSerial: 'યુએસબી સીરીયલ', disconnect: 'ડિસ્કનેક્ટ કરો', quickInfoTitle: 'ઝડપી માહિતી', quickInfoDesc: 'ડૉક્ટરો અને હેલ્પલાઇન શોધવા માટે ડાબી પેનલનો ઉપયોગ કરો. ઉપકરણ સાથે જોડાવા અને લોગ જોવા માટે કેન્દ્ર પેનલનો ઉપયોગ કરો.', helplinesTitle: 'હેલ્પલાઇન', hospitalHelpline: 'હોસ્પિટલ હેલ્પલાઇન', police: 'પોલીસ', ambulance: 'એમ્બ્યુલન્સ', analyze: 'વિશ્લેષણ કરો', analyzing: 'વિશ્લેષણ કરી રહ્યું છે...', aiAnalysis: 'AI વિશ્લેષણ:', aiAnalyzing: 'AI સાથે લોગનું વિશ્લેષણ...', aiAnalysisFailed: 'AI વિશ્લેષણ નિષ્ફળ થયું:' },
  kn: { findTitle: 'ವೈದ್ಯರನ್ನು ಹುಡುಕಿ', findDesc: 'ತಜ್ಞ ವೈದ್ಯರನ್ನು ಹುಡುಕಿ, ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಿಸಿ ಮತ್ತು ನಿರ್ದೇಶನಗಳು ಮತ್ತು ಸಂಪರ್ಕವನ್ನು ಪಡೆಯಿರಿ.', nearbyDoctors: 'ಹತ್ತಿರದ ವೈದ್ಯರನ್ನು ಹುಡುಕಿ', nearbyHospitals: 'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳನ್ನು ಹುಡುಕಿ', serialMonitor: 'ಸೀರಿಯಲ್ ಮಾನಿಟರ್', cmdPlaceholder: 'ಕಳುಹಿಸಲು ಆದೇಶ ಅಥವಾ ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ', send: 'ಕಳುಹಿಸು', viewHistory: 'ಇತಿಹಾಸವನ್ನು ವೀಕ್ಷಿಸಿ:', autoTranslate: 'ಸ್ವಯಂ-ಅನುವಾದ', directions: 'ನಿರ್ದೇಶನಗಳು', whatsapp: 'ವಾಟ್ಸಾಪ್', phoneNotAvailable: 'ಫೋನ್ ಲಭ್ಯವಿಲ್ಲ', language: 'ಭಾಷೆ', bluetooth: 'ಬ್ಲೂಟೂತ್', usbSerial: 'ಯುಎಸ್‌ಬಿ ಸೀರಿಯಲ್', disconnect: 'ಸಂಪರ್ಕ ಕಡಿತಗೊಳಿಸಿ', quickInfoTitle: 'ತ್ವರಿತ ಮಾಹಿತಿ', quickInfoDesc: 'ವೈದ್ಯರು ಮತ್ತು ಸಹಾಯವಾಣಿಗಳನ್ನು ಹುಡುಕಲು ಎಡ ಫಲಕವನ್ನು ಬಳಸಿ. ಸಾಧನಕ್ಕೆ ಸಂಪರ್ಕಿಸಲು ಮತ್ತು ಲಾಗ್‌ಗಳನ್ನು ವೀಕ್ಷಿಸಲು ಕೇಂದ್ರ ಫಲಕವನ್ನು ಬಳಸಿ.', helplinesTitle: 'ಸಹಾಯವಾಣಿಗಳು', hospitalHelpline: 'ಆಸ್ಪತ್ರೆ ಸಹಾಯವಾಣಿ', police: 'ಪೊಲೀಸ್', ambulance: 'ಆಂಬ್ಯುಲೆನ್ಸ್', analyze: 'ವಿಶ್ಲೇಷಿಸಿ', analyzing: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...', aiAnalysis: 'AI ವಿಶ್ಲೇಷಣೆ:', aiAnalyzing: 'AI ನೊಂದಿಗೆ ಲಾಗ್‌ಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...', aiAnalysisFailed: 'AI ವಿಶ್ಲೇಷಣೆ ವಿಫಲವಾಗಿದೆ:' },
  ml: { findTitle: 'ഡോക്ടർമാരെ കണ്ടെത്തുക', findDesc: 'വിദഗ്ദ്ധരായ ഡോക്ടർമാരെ തിരയുക, പ്രൊഫൈൽ കാണുക, ദിശകളും കോൺടാക്റ്റും നേടുക.', nearbyDoctors: 'അടുത്തുള്ള ഡോക്ടർമാരെ തിരയുക', nearbyHospitals: 'അടുത്തുള്ള ആശുപത്രികൾ തിരയുക', serialMonitor: 'സീരിയൽ മോണിറ്റർ', cmdPlaceholder: 'അയയ്ക്കാൻ ഒരു കമാൻഡ് അല്ലെങ്കിൽ സന്ദേശം ടൈപ്പ് ചെയ്യുക', send: 'അയയ്ക്കുക', viewHistory: 'ചരിത്രം കാണുക:', autoTranslate: 'യാന്ത്രികമായി വിവർത്തനം ചെയ്യുക', directions: 'വഴികൾ', whatsapp: 'വാട്ട്‌സ്ആപ്പ്', phoneNotAvailable: 'ഫോൺ ലഭ്യമല്ല', language: 'ഭാഷ', bluetooth: 'ബ്ലൂടൂത്ത്', usbSerial: 'യുഎസ്ബി സീരിയൽ', disconnect: 'വിച്ഛേദിക്കുക', quickInfoTitle: 'ദ്രുത വിവരങ്ങൾ', quickInfoDesc: 'ഡോക്ടർമാരെയും ഹെൽപ്പ് ലൈനുകളെയും കണ്ടെത്താൻ ഇടത് പാനൽ ഉപയോഗിക്കുക. ഉപകരണവുമായി ബന്ധിപ്പിക്കുന്നതിനും ലോഗുകൾ കാണുന്നതിനും സെന്റർ പാനൽ ഉപയോഗിക്കുക.', helplinesTitle: 'ഹെൽപ്പ് ലൈനുകൾ', hospitalHelpline: 'ആശുപത്രി ഹെൽപ്പ് ലൈൻ', police: 'പോലീസ്', ambulance: 'ആംബുലൻസ്', analyze: 'വിശകലനം ചെയ്യുക', analyzing: 'വിശകലനം ചെയ്യുന്നു...', aiAnalysis: 'AI വിശകലനം:', aiAnalyzing: 'AI ഉപയോഗിച്ച് ലോഗുകൾ വിശകലനം ചെയ്യുന്നു...', aiAnalysisFailed: 'AI വിശകലനം പരാജയപ്പെട്ടു:' },
  pa: { findTitle: 'ਡਾਕਟਰ ਲੱਭੋ', findDesc: 'ਮਾਹਰ ਡਾਕਟਰਾਂ ਦੀ ਖੋਜ ਕਰੋ, ਪ੍ਰੋਫਾਈਲ ਦੇਖੋ ਅਤੇ ਦਿਸ਼ਾ-ਨਿਰਦੇਸ਼ ਅਤੇ ਸੰਪਰਕ ਪ੍ਰਾਪਤ ਕਰੋ।', nearbyDoctors: 'ਨੇੜਲੇ ਡਾਕਟਰਾਂ ਦੀ ਖੋਜ ਕਰੋ', nearbyHospitals: 'ਨੇੜਲੇ ਹਸਪਤਾਲਾਂ ਦੀ ਖੋਜ ਕਰੋ', serialMonitor: 'ਸੀਰੀਅਲ ਮਾਨੀਟਰ', cmdPlaceholder: 'ਭੇਜਣ ਲਈ ਇੱਕ ਕਮਾਂਡ ਜਾਂ ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ', send: 'ਭੇਜੋ', viewHistory: 'ਇਤਿਹਾਸ ਦੇਖੋ:', autoTranslate: 'ਆਟੋ-ਅਨੁਵਾਦ', directions: 'ਦਿਸ਼ਾ-ਨਿਰਦੇਸ਼', whatsapp: 'ਵਟਸਐਪ', phoneNotAvailable: 'ਫੋਨ ਉਪਲਬਧ ਨਹੀਂ ਹੈ', language: 'ਭਾਸ਼ਾ', bluetooth: 'ਬਲੂਟੁੱਥ', usbSerial: 'USB ਸੀਰੀਅਲ', disconnect: 'ਡਿਸਕਨੈਕਟ ਕਰੋ', quickInfoTitle: 'ਤੁਰੰਤ ਜਾਣਕਾਰੀ', quickInfoDesc: 'ਡਾਕਟਰਾਂ ਅਤੇ ਹੈਲਪਲਾਈਨਾਂ ਨੂੰ ਲੱਭਣ ਲਈ ਖੱਬੇ ਪੈਨਲ ਦੀ ਵਰਤੋਂ ਕਰੋ। ਡਿਵਾਈਸ ਨਾਲ ਕਨੈਕਟ ਕਰਨ ਅਤੇ ਲੌਗ ਦੇਖਣ ਲਈ ਸੈਂਟਰ ਪੈਨਲ ਦੀ ਵਰਤੋਂ ਕਰੋ।', helplinesTitle: 'ਹੈਲਪਲਾਈਨਾਂ', hospitalHelpline: 'ਹਸਪਤਾਲ ਹੈਲਪਲਾਈਨ', police: 'ਪੁਲਿਸ', ambulance: 'ਐਂਬੂਲੈਂਸ', analyze: 'ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ', analyzing: 'ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...', aiAnalysis: 'AI ਵਿਸ਼ਲੇਸ਼ਣ:', aiAnalyzing: 'AI ਨਾਲ ਲੌਗਸ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਨਾ...', aiAnalysisFailed: 'AI ਵਿਸ਼ਲੇਸ਼ਣ ਅਸਫਲ ਰਿਹਾ:' },
  ur: { findTitle: 'ڈاکٹر تلاش کریں', findDesc: 'ماہر ڈاکٹروں کو تلاش کریں، پروفائل دیکھیں اور ہدایات اور رابطہ حاصل کریں۔', nearbyDoctors: 'قریبی ڈاکٹروں کو تلاش کریں', nearbyHospitals: 'قریبی ہسپتالوں کو تلاش کریں', serialMonitor: 'سیریل مانیٹر', cmdPlaceholder: 'بھیجنے کے لیے کوئی کمانڈ یا پیغام ٹائپ کریں', send: 'بھیجیں', viewHistory: 'تاریخ دیکھیں:', autoTranslate: 'خودکار ترجمہ', directions: 'ہدایات', whatsapp: 'واٹس ایپ', phoneNotAvailable: 'فون دستیاب نہیں ہے', language: 'زبان', bluetooth: 'بلوٹوتھ', usbSerial: 'USB سیریل', disconnect: 'منقطع کریں', quickInfoTitle: 'فوری معلومات', quickInfoDesc: 'ڈاکٹروں اور ہیلپ لائنز کو تلاش کرنے کے لیے بائیں پ্যাল کا استعمال کریں۔ ڈیوائس سے منسلک ہونے اور لاگز دیکھنے کے लिए سنٹر پینل کا استعمال کریں۔', helplinesTitle: 'ہیلپ لائنز', hospitalHelpline: 'ہسپتال ہیلپ لائن', police: 'پولیس', ambulance: 'ایمبولینس', analyze: 'تجزیہ کریں', analyzing: 'تجزیہ کیا جا رہا ہے...', aiAnalysis: 'AI تجزیہ:', aiAnalyzing: 'AI کے ساتھ لاگز کا تجزیہ...', aiAnalysisFailed: 'AI تجزیہ ناکام ہو گیا:' },
};